# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d524576fbc012862ba4b15f6d77fdef8a5b0d875b83e9b984d3b0a2ba8cbfc7ef4946fc8ac066977543d14dff74b5df6cc562c7dbf02a4d9eaed2bead14fca2

test:
  secret_key_base: 21064bdbccd549bceb4b7b708648ed588f16964afd540622092f7a5f618a3735a8e3f29717872e8124390bbbbf4348ea30e2359bd4ca165f873ba0ab4463b52e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
